### ISSUE TITLE
thingesp module import

### ISSUE THREAD

**Issue by cheattheweb** [EiadurRahman/semiautomated_plant_care#3]
# Code organization
the send_msg() function is defined outside the Client class, why?
if it is closely related to the functionality of the Client Class,
consider moving it inside the class

**Comment by cheattheweb** [comment]
you have also imported usocket, ustruct and os
Why?
remove them if not needed

**Comment by EiadurRahman** [comment]
> # Code organization
> the send_msg() function is defined outside the Client class, why? if it is closely related to the functionality of the Client Class, consider moving it inside the class

did all the necessary changes you suggested

**Comment by cheattheweb** [comment]
add some comments, about the pins, d1, d2
What they do? something like that, Or Pin name

**Comment by cheattheweb** [comment]
Where is the `send_msg()` now?
